# Generated by Django 6.1 on 2026-08-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the auto-generated <title>. Aim for ≤60 characters.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description shown in search results. Aim for ≤155 characters.', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='1200×630 recommended. Falls back to the site default OG image.', null=True, upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank unless this content is duplicated elsewhere.')),
                ('noindex', models.BooleanField(default=False, help_text='Exclude this page from search engines.')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=280)),
                ('client_name', models.CharField(blank=True, help_text='Free-text for now -- becomes a FK to testimonials.Client in Phase 11.', max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage featured-work section.')),
                ('is_confidential', models.BooleanField(default=False, help_text='Hide client name on the public page.')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='industries.industry')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
