# Generated by Django 6.1 on 2026-08-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank unless this content is duplicated elsewhere.'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Full service description shown on the detail page. Rich text editing lands with the CKEditor pass; plain text/paragraphs render fine today.'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Exclude this page from search engines.'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630 recommended. Falls back to the site default OG image.', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='service',
            name='related_industries',
            field=models.ManyToManyField(blank=True, related_name='related_services', to='industries.industry'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description shown in search results. Aim for ≤155 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides the auto-generated <title>. Aim for ≤60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'verbose_name_plural': 'Service Process Steps',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
