# Generated by Django 6.1 on 2026-08-06 11:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200)),
                ('link_label', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Announcement Banner',
                'verbose_name_plural': 'Announcement Banner',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('header_primary', 'Header — Primary'), ('header_utility', 'Header — Utility (top bar)'), ('footer_col_1', 'Footer — Column 1'), ('footer_col_2', 'Footer — Column 2'), ('footer_col_3', 'Footer — Column 3'), ('footer_legal', 'Footer — Legal row')], max_length=30, unique=True)),
                ('label', models.CharField(help_text='Internal label, not shown on site.', max_length=100)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Electro Mnemonic Engineering Consultancy', max_length=150)),
                ('short_name', models.CharField(default='EMEC', max_length=50)),
                ('tagline', models.CharField(blank=True, help_text='Short brand line used near the logo/footer.', max_length=200)),
                ('founding_year_bs', models.CharField(default='2070', max_length=10)),
                ('founding_year_ad', models.PositiveIntegerField(default=2013)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Optional alternate logo for dark backgrounds/dark mode.', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_email', models.EmailField(default='info@emec.com.np', max_length=254)),
                ('primary_phone', models.CharField(default='+977-1-0000000', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('footer_about_text', models.TextField(blank=True)),
                ('footer_copyright_text', models.CharField(blank=True, help_text="e.g. '© {year} EMEC — Electro Mnemonic Engineering Consultancy'", max_length=255)),
                ('group_intro_text', models.TextField(blank=True, help_text='Short intro explaining EMEC as the parent of the group (Nepal Agro Yantra, Ojas Solutions, RC Interior…).')),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=30)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=30)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('default_meta_description', models.CharField(blank=True, max_length=160)),
                ('show_careers', models.BooleanField(default=True)),
                ('show_blog', models.BooleanField(default=True)),
                ('show_research', models.BooleanField(default=True)),
                ('show_training', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter_x', 'X (Twitter)'), ('github', 'GitHub'), ('tiktok', 'TikTok')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Absolute path (/services/) or full URL. Leave blank if this is a dropdown-only parent.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier from the UI kit.', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
            },
        ),
    ]
