# Generated by Django 6.1 on 2026-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='industries/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
